name: EVM Deployer Boilerplate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        network: [hardhat]
        solidity_version: [0.8.9, 0.8.10]
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (required for many Solidity tooling)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install Yarn and dependencies
      - name: Install Yarn and dependencies
        run: |
          npm install --global yarn
          yarn install

      # Set up Solidity version
      - name: Set Solidity version
        # copy hardhat.config.compiler-{version}.js to hardhat.config.js
        run: |
          echo "Using Solidity version ${{ matrix.solidity_version }}"
          cp .travisci/hardhat.config.compiler-${{ matrix.solidity_version }}.js hardhat.config.js

      # Run build and test for the specified network and Solidity version
      - name: Run local CI process
        env:
          NETWORK: ${{ matrix.network }}
          SOLC_VERSION: ${{ matrix.solidity_version }}
        run: yarn ci
